### ISSUE TITLE
BiocView Metabolomics instead of (or addition to) Proteomics ?

### ISSUE THREAD

**Issue by sneumann** [girke-lab/ChemmineOB#15]
Hi, I have difficulties seeing why Chemmine* have BiocView Proteomics,
and would rather expect Metabolomics. This becomes relevant for the 
automatic docker container creation https://hub.docker.com/r/bioconductor/devel_metabolomics2/
Please add Metabolomics, possibly remove Proteomics, unless there is a reason 
to have both. Yours, Steffen

**Comment by tgirke** [comment]
Thanks for the suggestion. Adding Metabolomics makes sense. It may not have been an option when we added this the first time. We probably want to keep Proteomics since we use it a lot for drug-target work where proteomics is just as important. 

Kevin: this refers to the BiocView section in the Description file of each package that are used to classify packages by their broader functionality.
